validate ParseRangeString return value in EvaluateThreshold
atc0005/go-nagios pull request #234
Opened 2024-01-14 10:40 UTC by Tommi2Day

this PR adds checking of nil returns from ParseRangeString in EvaluateThreshold. it returns UNKNOWN state result and an error message.

second I added 2 tests to check this expected behavior

should fix #233

2024-01-15 02:26 UTC, atc0005 commented
@Tommi2Day thank you for submitting this PR. I should be able to take a look at this in the next few days and get back to you.

The addition of tests is much appreciated!

2024-01-15 20:54 UTC, Tommi2Day commented
added fix for #235

2024-01-16 12:06 UTC, atc0005 requested changes
Overall, this is great. Many thanks for taking the time to report the problems and craft a set of changes to resolve them. The inclusion of test cases is especially appreciated.

I've highlighted a few spots for further discussion. Please let me know if I can clarify anything.

2024-01-16 12:06 UTC, atc0005 commented on range.go
> +				err := fmt.Errorf("invalid critical threshold: %s ", perfData[i].Crit)
Minor: We could adjust this in a follow-up PR, but wanted to note it while it was on my mind.

One of the approaches used thus far in this library is providing wrapped static errors. I don't know that is the *right* approach to use, but for consistency what do you think about adding to the sentinel error collection here:

https://github.com/atc0005/go-nagios/blob/7a6e9212a75d7cf063a1d0c787c74a4cb847f1a1/nagios.go#L72-L74

Something like:

```go
	// ErrInvalidRangeThreshold indicates that a given range threshold is not
	// in a supported format.
	ErrInvalidRangeThreshold = errors.New("invalid range threshold")
```

and line 154 becomes something like one of:

```go
err := fmt.Errorf("failed to parse critical range string %s: %w ", perfData[i].Crit, ErrInvalidRangeThreshold )
```

```go
err := fmt.Errorf("error parsing critical range string %s: %w ", perfData[i].Crit, ErrInvalidRangeThreshold )
```

2024-01-16 12:06 UTC, atc0005 commented on range.go
> +				err := fmt.Errorf("invalid warning threshold: %s ", perfData[i].Warn)
Same feedback here as line 154.

2024-01-16 17:17 UTC, closed without merging